### ISSUE TITLE
Use of Weights and offset for models

### ISSUE THREAD

**Issue by naveranoc** [tidymodels/embed#106]
In insurance, the use of weights is very important, it could be important that these steps also include the use of these steps for when categories are joined.

**Comment by juliasilge** [comment]
You can read more about [case weights](https://github.com/tidymodels/planning/tree/main/case-weights) and our plan to implement them.

**Comment by naveranoc** [comment]
Hello @juliasilge, thank you very much for your answer, but I have a couple of doubts, for example, if we used a poisson regression model, in which it had an exposure variable (EXPO) (Proportion of the time in which an observation was under observation), I could not use this variable as a weight within the regression model or within a regression tree, it should enter as an offset to the model, despite the fact that I mark it within tidymodels with the role of case_weight. How would the pre-processes work in this case, for example step_discretize_cart?, would he use the poisson loss function, or would he use anova?.

Sorry for the long message, and I appreciate your help

**Comment by EmilHvitfeldt** [comment]
The appropiate steps now support case-weights, as the example `step_discretize_cart()` lists its support here: https://embed.tidymodels.org/reference/step_discretize_cart.html#case-weights

You can read more about case weights are used in tidymodels here:

- https://recipes.tidymodels.org/reference/case_weights.html
- https://www.tidyverse.org/blog/2022/05/case-weights/
- https://www.tidyverse.org/blog/2022/07/tidymodels-2022-q2/
