### ISSUE TITLE
Allow step_collapse_stringdist to accept different distance methods 

### ISSUE THREAD

**Issue by skasowitz** [tidymodels/embed#152]
Hello,
There are situations where the default OSA distance metric is not ideal for collapsing factor levels. It would be great if another method could be passed to `stringdistmatrix`.
_e.g._

```r
library(recipes)
library(tibble)
data0 <- tibble(
  x1 = c("a", "b", "d", "e", "sfgsfgsd", "hjhgfgjgr"),
  x2 = c("ak", "b", "djj", "e", "hjhgfgjgr", "hjhgfgjgr")
 )

rec <- recipe(~., data = data0) %>%
  step_collapse_stringdist(all_predictors(), method = 'jw', distance = 0.1) %>%
  prep()
```

Thanks,
Seth

**Comment by EmilHvitfeldt** [comment]
Hello @skasowitz thanks for the feature request! we will be working on this when get get back to {embed} development.
