### ISSUE TITLE
Metrice argument for step_umap function

### ISSUE THREAD

**Issue by jackobenco016** [tidymodels/embed#154]
Hello,

Is there an argument like "metric" for the step_umap function ?

Thanks in advance

**Comment by EmilHvitfeldt** [comment]
Hello @jackobenco016 👋 

You can specify the `metric` argument to `umap()` by using the `options` argument in `step_umap()` like so.

I'm going to keep this issue open, as I think that this argument should be a direct argument in `step_umap()`

``` r
library(embed)
library(recipes)
library(ggplot2)

split <- seq.int(1, 150, by = 9)
tr <- iris[-split, ]
te <- iris[split, ]

set.seed(11)
supervised <-
  recipe(Species ~ ., data = tr) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors()) %>%
  step_umap(all_predictors(), outcome = vars(Species), num_comp = 2, 
            options = list(metric = "hamming")) %>%
  prep(training = tr)

theme_set(theme_bw())

bake(supervised, new_data = te, Species, starts_with("umap")) %>%
  ggplot(aes(x = UMAP1, y = UMAP2, col = Species)) +
  geom_point(alpha = .5)
```

![](https://i.imgur.com/aIeKJ8G.png)

<sup>Created on 2023-01-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jackobenco016** [comment]
Okay thanks for your answer ! 
How can I use a metric that I have defined ? 

Thanks for your answer !
