### ISSUE TITLE
Option to estimate models with lme4 (or similar)

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/embed#2]
It might be nice to have an option to estimate pooled likelihood encodings in `lme4`, which is faster at the cost of less flexibility.

This is a silly example, but:

```
library(rstanarm)
library(lme4)
library(microbenchmark)

fit_stan <- function() stan_lmer(Sepal.Width ~ 1|Species, data = iris)
fit_lme4 <- function() lmer(Sepal.Width ~ 1|Species, data = iris)

microbenchmark(
  fit_stan(),
  fit_lme4(),
  times = 5
)
```

Each `stan_lmer` fit takes 13 seconds on my computer, but `lmer` takes only a fifth of a second, which could add up quickly if users are calculating encodings across many resampled datasets.

I'd be happy to make a PR (won't be able to start working on it till next Monday), but wanted to see if you're interested first, and if you have anything thoughts on an inferface.

**Comment by topepo** [comment]
I considered doing that and didn't for two reasons:

* with `stan` you have the (limited) ability to moderate how much shrinkage occurs
* with `lme*` you inherit a direct dependency to `nlopt` and that has bitten me countless times when getting people to install `caret` during workshops. [This post](https://github.com/jyypma/nloptr/issues/34#issuecomment-339343868) describes the issue (and doesn't look to be closed yet). 

I'd say okay to using `lme4` with a `stan = TRUE` flag for `step_embed`. No need to create another step.

**Comment by topepo** [comment]
Done. Thanks
