### ISSUE TITLE
Error loading and baking with step_umap for new data

### ISSUE THREAD

**Issue by goleng** [tidymodels/embed#20]
Hi, 

Thanks a lot for this embedding step! I'm a big fan of this package and it makes easy to accomplish a lot with just few lines of code. 

I recently encountered a problem whilst trying to reload a saved `step_umap` object to bake on new data. The error message is shown below: 

`Error in .External(list(name = "CppMethod__invoke_void", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address ` 

I have done a bit of Google search for the said error and did find this git issue [https://github.com/jlmelville/uwot/issues/19](https://github.com/jlmelville/uwot/issues/19) but I wanted to check if there exist any workaround in the `embed` package implementation. 

Thanks!

**Comment by topepo** [comment]
😩 That's not very convenient. I'll look into a way to serialize that or make the `recipes` interface a little better.

**Comment by goleng** [comment]
>  That's not very convenient. I'll look into a way to serialize that or make the `recipes` interface a little better.

That will be helpful and thanks a lot!

**Comment by topepo** [comment]
I haven't made any headway on this since it will take someone with specialized Rcpp know-how to fix it. 

I'll close and open another issue if/when there is progress.
