### ISSUE TITLE
tidyr updates

### ISSUE THREAD

**Issue by topepo** [tidymodels/embed#24]
Maybe fine with the changes to `recipes` though.

**Comment by topepo** [comment]
Nope. We need to change `tidyr::nest(.key = "woe_table")`. 

There is a template for the solution [here](https://tidyr.tidyverse.org/dev/articles/in-packages.html#new-syntax-for-nest). This change should look something like:

```
  if (tidyr_new_interface()) {
    nested_info <- tidyr::nest(woe_table = some_variable_list)
  } else {
    nested_info <- tidyr::nest(.key = "woe_table")
  }
``` 
I'm not sure what `some_variable_list` should be. @Athospd can you fill this in?

**Comment by Athospd** [comment]
@topepo I think you got it. I tested here and it is working fine. I just move the `dplyr::group_by()` line inside de old tidyr clause.
