### ISSUE TITLE
Reformat readme

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/embed#35]
The readme has most of the essential information but is missing titles and sections as is used in most other tidymodels packages

- [x]  Name
- [x]  Bagdes
- [ ]  hex logo
- [x]  Introduction
- [x]  Installation
- [ ]  examples/learning more/Usage
- [x]  Contributing

See https://github.com/tidymodels/broom for example

**Comment by topepo** [comment]
No badge currently
