### ISSUE TITLE
Broken link to article.

### ISSUE THREAD

**Issue by niszet** [tidymodels/embed#38]
Hello,

I found a broken link to http://jse.amstat.org/v23n2/kim.pdf (Kim and Escobedo-Land (2015)(pdf)) in the page https://tidymodels.github.io/embed/articles/Applications/GLM.html .

Could you check when you update the site?

**Comment by topepo** [comment]
Their site is borked. [This link](https://amstat.tandfonline.com/doi/pdf/10.1080/10691898.2015.11889737) appears to work.
