### ISSUE TITLE
Multiple features

### ISSUE THREAD

**Issue by rajshah4** [tidymodels/embed#5]
Could you add an example of how you would use embed when you want to create/get embeddings from multiple categorical variables?  My assumption is you would have multiple embedding layers, but train the model at once.  Is that possible with embed?  Can you provide an example of that?  I hope this makes sense.  (This would be like Fig. 1 in the Guo & Berkhahn paper)

**Comment by topepo** [comment]
Right now it would estimate those separately. You can list multiple predictors in the step.

**Comment by topepo** [comment]
The current version contains changes to estimate multiple embeddings at once.
