### ISSUE TITLE
step_lencode_bayes() takes forever

### ISSUE THREAD

**Issue by agilebean** [tidymodels/embed#50]
I successfully applied `step_lencode_glm`and `step_embed` to small datasets.
However, applying `step_lencode_bayes` takes forever meaning it hasn't finished for very small datasets like ameshousing after 1h - which is the time to abort for me.
Does this have method-intrinsic reasons? 
Furthermore, I am confused by the output message `Linear embedding for factors via GLM for all_nominal()`.
What bayesian model is exactly implemented here? A reference to paper would be great, as I need it for publication.

Here is a reproducible example.

```
dataset <- AmesHousing::make_ames()
target.label <- "Sale_Price"
target <- dataset[[target.label]]
features.labels <- dataset %>% select(-target.label) %>% names

train.index <- createDataPartition(target, p = 0.8, list = FALSE) %>% as.vector()
training.set <- dataset[train.index, ]
testing.set <- dataset[-train.index, ]

features.labels <-training.set %>% 
    select(-target.label) %>% names %T>% print
  
recipe.base <- features.labels %>% 
    paste(collapse = " + ") %>% 
    paste(target.label, "~", .) %>% 
    as.formula %>% 
    recipe(training.set)

recipe.encoding <- recipe.base %>% 
    step_lencode_bayes(all_nominal(), outcome = vars(target.label)) 

# this step takes forever
prep.encoding <- prep(recipe.encoding, training = training.set, retain = TRUE)

training.set.juiced <- juice(prep.encoding) %T>% print
testing.set.baked <- prep.encoding %>% bake(testing_original)
```

Running the `prep` step on the first 50 rows of the training set throws this cryptic error on which I would appreciate an explanation:
```
Error: grouping factors must have > 1 sampled level
In addition: Warning messages:
1: There were 1 divergent transitions after warmup. Increasing adapt_delta above 0.95 may help. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
```

Any hints welcome!

**Comment by topepo** [comment]
That title was a typo and has been fixed. 

"Too long" is always subjective but it's fairly well known that MCMC methods for Bayesian analysis are not usually fast. 

Also, keep in mind that when you use this with `tune` or `caret`, this slow method is resampled multiple times. You might consider using the mixed model function.
