### ISSUE TITLE
Implementation of `step_tsne` ?

### ISSUE THREAD

**Issue by Cardosaum** [tidymodels/embed#51]
Hi! 

I was just pondering if a function to conduct `t-sne` analysis could be implemented. 
Looking for dimensionality reduction options in the `recipes` package, I found that the `embed` package contains `step_umap` (and, of course, the `recipes` package contains `step_pca`).

I'd like to thank you guys for the work you are doing in this and in many other `R` packages. :)

**Comment by topepo** [comment]
No. We included UMAP since it can be projected on new data. tSNE can't (at least, the last time that I looked).

**Comment by Cardosaum** [comment]
Ok, I understand.

Thanks for the quick answer!
