### ISSUE TITLE
Problem with embed installation 

### ISSUE THREAD

**Issue by data-datum** [tidymodels/embed#55]
> install.packages("embed")
Installing package into ‘/home/roxana/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
probando la URL 'https://cloud.r-project.org/src/contrib/embed_0.1.1.tar.gz'
Content type 'application/x-gzip' length 46880 bytes (45 KB)
==================================================
downloaded 45 KB

* installing *source* package ‘embed’ ...
** package ‘embed’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading

 *** caught segfault ***
address 0x7fc0dd39d008, cause 'invalid permissions'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(package = package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, partial = TRUE)
 7: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
 8: suppressPackageStartupMessages(loadNamespace(package = package,     lib.loc = lib.loc, keep.source = keep.source, keep.parse.data = keep.parse.data,     partial = TRUE))
 9: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, compress = compress, set.install.dir = set.install.dir)
10: tools:::makeLazyLoading("embed", "/home/roxana/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-embed/00new",     keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = "/home/roxana/R/x86_64-pc-linux-gnu-library/3.6/embed")
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)
ERROR: lazy loading failed for package ‘embed’
* removing ‘/home/roxana/R/x86_64-pc-linux-gnu-library/3.6/embed’
Warning in install.packages :
  installation of package ‘embed’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpgjvCcx/downloaded_packages’

My sessionInfo() details as follows:

sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=es_AR.UTF-8       LC_NUMERIC=C               LC_TIME=es_AR.UTF-8       
 [4] LC_COLLATE=es_AR.UTF-8     LC_MONETARY=es_AR.UTF-8    LC_MESSAGES=es_AR.UTF-8   
 [7] LC_PAPER=es_AR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=es_AR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.6.3   Matrix_1.2-18    magrittr_1.5     R6_2.4.1         generics_0.0.2  
 [6] tools_3.6.3      whisker_0.4      base64enc_0.1-3  Rcpp_1.0.5       reticulate_1.16 
[11] keras_2.3.0.0    tensorflow_2.2.0 grid_3.6.3       zeallot_0.1.0    jsonlite_1.7.0  
[16] tfruns_1.4       lattice_0.20-40

**Comment by topepo** [comment]
I've never seen that before. Have you ever installed anything using conda? Also, can you shut down all R instances and try again? 

`embed` is all R code; I can't imagine what it would do to cause a seg fault; it makes me thing that there is something wrong with your R installation.

**Comment by data-datum** [comment]
No, I have not installed conda in my computer. I have restarted my laptop but the problem remains. Here my session info details with devtools package: 
> devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Ubuntu 20.04.1 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language es_AR:es                    
 collate  es_AR.UTF-8                 
 ctype    es_AR.UTF-8                 
 tz       America/Argentina/Cordoba   
 date     2020-09-01                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.3)
 backports     1.1.8   2020-06-17 [1] CRAN (R 3.6.3)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.6.3)
 callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.3)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.3)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.3)
 devtools      2.3.0   2020-04-10 [1] CRAN (R 3.6.3)
 digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 3.6.3)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.3)
 fs            1.4.2   2020-06-30 [1] CRAN (R 3.6.3)
 generics      0.0.2   2018-11-29 [1] CRAN (R 3.6.3)
 glue          1.4.1   2020-05-13 [1] CRAN (R 3.6.3)
 jsonlite      1.7.0   2020-06-25 [1] CRAN (R 3.6.3)
 keras         2.3.0.0 2020-05-19 [1] CRAN (R 3.6.3)
 lattice       0.20-40 2020-02-19 [4] CRAN (R 3.6.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.3)
 Matrix        1.2-18  2019-11-27 [4] CRAN (R 3.6.1)
 memoise       1.1.0   2017-04-21 [3] CRAN (R 3.5.0)
 pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 3.6.3)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 3.6.3)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.3)
 processx      3.4.3   2020-07-05 [1] CRAN (R 3.6.3)
 ps            1.3.3   2020-05-08 [1] CRAN (R 3.6.3)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.3)
 Rcpp          1.0.5   2020-07-06 [1] CRAN (R 3.6.3)
 remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.3)
 reticulate    1.16    2020-05-27 [1] CRAN (R 3.6.3)
 rlang         0.4.7   2020-07-09 [1] CRAN (R 3.6.3)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.3)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.3)
 sessioninfo   1.1.1   2018-11-05 [3] CRAN (R 3.5.1)
 tensorflow    2.2.0   2020-05-11 [1] CRAN (R 3.6.3)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
 tfruns        1.4     2018-08-25 [1] CRAN (R 3.6.3)
 usethis       1.6.1   2020-04-29 [1] CRAN (R 3.6.3)
 whisker       0.4     2019-08-28 [1] CRAN (R 3.6.3)
 withr         2.2.0   2020-04-20 [1] CRAN (R 3.6.3)
 zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.6.3)

[1] /home/roxana/R/x86_64-pc-linux-gnu-library/3.6
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library

**Comment by data-datum** [comment]
I installed the latest version from Github (not the CRAN version) and it already worked!
