### ISSUE TITLE
Q: possible data leakage if the embedding using the label information?

### ISSUE THREAD

**Issue by ajing** [tidymodels/embed#56]
I am just wondering about features created by embeddings using the label information. Is there any data leakage problem if I try to build a model with those added features?

**Comment by alexpghayes** [comment]
Yes. In practice you will need to do something to prevent this. Using some
sort of out-of-sample embeddings is my recommendation.

**Comment by topepo** [comment]
Or making sure that you resample it to make sure.

**Comment by ajing** [comment]
Thanks, Alex and Max! Could you guys provide an example of how to train embedding by resampling?

**Comment by topepo** [comment]
You would train in the usual way but resample the recipe to make sure that you are not overfitting. If you are not tuning, then you could use `tune::fit_resamples()`. Otherwise, `tune::tune_grid()` would be a good choice.
