### ISSUE TITLE
The year 2106 resurfaces

### ISSUE THREAD

**Issue by eddelbuettel** [tidymodels/embed#6]
> Guo, C and Berkhahn F (2106) 

I think I reported that before :)

**Comment by eddelbuettel** [comment]
Should have added source -- the associated website still has it as 2106:

![image](https://user-images.githubusercontent.com/673121/41729104-04cf26c2-753e-11e8-9a0d-78df5167aeca.png)

which should be fixable by just re-running the generator as you seem to have fixed it in the sources.

**Comment by eddelbuettel** [comment]
I am not sure how much you care but your recent package upload also has you again as Kuhn Max:

```sh
Author:  Kuhn Max [aut, cre], Hadley Wickham [aut], RStudio [cph, fnd]
Maintainer: Kuhn Max <max at rstudio.com>
```

**Comment by topepo** [comment]
Should be good now. Thanks
