### ISSUE TITLE
Add novel-value handing method to step_woe

### ISSUE THREAD

**Issue by kylegilde** [tidymodels/embed#64]
Hi

I noticed that all the glm based steps have a method for handling novel values: "For novel levels, a slightly timmed average of the coefficients is returned."

Would it make sense to add the same handling method to step_woe?

**Comment by topepo** [comment]
They are very different models. We can do that in the likelihood encoding and embedding steps because of their probabilistic models. WoE doesn't have the same properties.

**Comment by kylegilde** [comment]
Hi Max,  

I really want to use WoE transformation in my project, but I need it to be able to handle novel values or else my script will fail. 

What if the user could specify novel values to be set to 0 like this other WoE encoder does?

http://contrib.scikit-learn.org/category_encoders/woe.html

Is there another way to handle novel values that I am overlooking?

Thanks

**Comment by topepo** [comment]
You can use `step_novel()` beforehand.
