### ISSUE TITLE
Moving some packages from import to suggest

### ISSUE THREAD

**Issue by lorenzwalthert** [tidymodels/embed#65]
This package has some very heavy (system) dependencies that are required in any case (via `Imports:`). Is it an option for you to move some of them into `Suggests:` to make a base installation lighter? As far as I understand this package, most recipes steps from this package require just one or two of these dependencies (like tensorflow), so if I only use say one step from this package, I technically don't need the majority of the dependencies in `Imports:`. This in particular matters in model deployment.

**Comment by juliasilge** [comment]
We think this is a good idea, and will work on making this change. The steps themselves will need to change as well, to check for installation.

**Comment by juliasilge** [comment]
Closed in #68
