### ISSUE TITLE
woe calculation in dictionary()

### ISSUE THREAD

**Issue by tonigril** [tidymodels/embed#70]
Why is woe different if I sort the outcome column? I get different woe values if in the first row of data the value of outcome column is 1 or 0.

mtcars_outcome_1_first <- mtcars
mtcar_outcome_0_first <- mtcars %>% arrange(am)

embed::dictionary(.data = mtcars_outcome_1_first %>% select(cyl, am), outcome = "am")
embed::dictionary(.data = mtcar_outcome_0_first %>% select(cyl, am), outcome = "am")

**Comment by juliasilge** [comment]
Notice that they have the same absolute value and are just in the opposite direction, much like PCA contributions:

``` r
library(embed)
#> Loading required package: recipes
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

mtcars %>% dictionary(outcome = "am", cyl)
#> # A tibble: 3 x 9
#>   variable predictor n_tot   n_0   n_1   p_0   p_1     woe outcome
#>   <chr>    <chr>     <int> <dbl> <dbl> <dbl> <dbl>   <dbl> <chr>  
#> 1 cyl      4            11     3     8 0.158 0.615  1.36   am     
#> 2 cyl      6             7     4     3 0.211 0.231  0.0918 am     
#> 3 cyl      8            14    12     2 0.632 0.154 -1.41   am
mtcars %>% arrange(am) %>% dictionary(outcome = "am", cyl)
#> # A tibble: 3 x 9
#>   variable predictor n_tot   n_0   n_1   p_0   p_1     woe outcome
#>   <chr>    <chr>     <int> <dbl> <dbl> <dbl> <dbl>   <dbl> <chr>  
#> 1 cyl      4            11     3     8 0.158 0.615 -1.36   am     
#> 2 cyl      6             7     4     3 0.211 0.231 -0.0918 am     
#> 3 cyl      8            14    12     2 0.632 0.154  1.41   am
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

You might [read the original source for this method](https://scholar.google.com/scholar?cluster=4365590320572354670&hl=en&as_sdt=0,45) if you want to dig deeper into why the relative values turn out the way they do.
