### ISSUE TITLE
add a sparse PCA step

### ISSUE THREAD

**Issue by topepo** [tidymodels/embed#73]
Via the `VBsparsePCA` package.

**Comment by juliasilge** [comment]
I'm not sure if you have specific reasons for wanting to use VBsparsePCA (Bayesian vs. not?), but there's a different implementation of PCA for sparse data in [irlba](https://cran.r-project.org/package=irlba) that I have used a fair amount with great results. It is what is used in [widyr](https://cran.r-project.org/package=widyr) as well.

**Comment by topepo** [comment]
I'll check it out. I saw `VBsparsePCA` when it was recently released and liked that it was fast and consistent with `prcomp()` results.

**Comment by topepo** [comment]
One difference is that `VBsparsePCA` applies the sparsity for the all the loadings for a predictor (so it has no affect on all components).  `irlba` doesn't use that constraint. Since I would only need to keep the rotation matrix, it might be easy to do both (`step_pca_sparse()` and `step_pca_sparse_bayes()`?).

**Comment by EmilHvitfeldt** [comment]
There is also a sparse pca step in the [MachineShop](https://github.com/brian-j-smith/MachineShop/blob/master/R/step_spca.R) package using the {elasticnet} package
