### ISSUE TITLE
Allow setting step_woe's "too many levels" warning threshold

### ISSUE THREAD

**Issue by smingerson** [tidymodels/embed#74]
## Issue
`step_woe` (via `add_woe()`, which is run during both `prep()` and `bake()`) warns if the dictionary contains more than 50 levels for the factor. It gets quite noisy when using the recipe in any resampling scheme. 

## Request

Condition the warning based on an argument to `step_woe()`, say `max_levels`. If any of the provided predictors have more unique values than `max_levels`, emit the warning during `prep()`. The default value would be 50 to match current behavior.

Happy to make a PR if you agree. The reprex below demonstrates the current behavior on `prep()` and `bake()`.
``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(tibble)
library(embed)
packageVersion("embed")
#> [1] '0.1.4'
set.seed(100)
data <- tibble(y = factor(sample(c('yes', 'no'), size = 52*10, replace = TRUE)),
               fct = factor(sample(c(letters, LETTERS), size = 52*10, replace = TRUE)))

rec <- recipe(y~fct, data = data) %>% 
  step_woe(fct, outcome = vars(y))

# warns on `prep()`, which I appreciate
prec <- prep(rec)  
#> Warning: Variable fct has 52 unique values. Is this expected? In case of numeric
#> variable, see ?step_discretize().

# also warns on `bake()`, which I don't  much.
bake(prec, new_data = data)
#> Warning: Variable fct has 52 unique values. Is this expected? In case of numeric
#> variable, see ?step_discretize().
#> # A tibble: 520 x 2
#>    y     woe_fct
#>    <fct>   <dbl>
#>  1 no    -0.590 
#>  2 yes   -0.254 
#>  3 no     0.192 
#>  4 no     0.817 
#>  5 yes   -0.542 
#>  6 yes   -0.0308
#>  7 no     0.123 
#>  8 no    -0.282 
#>  9 no     1.22  
#> 10 yes   -0.318 
#> # ... with 510 more rows
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by topepo** [comment]
I'd be happy with removing the message. A PR would be great.

**Comment by topepo** [comment]
Sorry for the delay on this. 

I changed the warning to look for cases where the number of data points in a particular category are low enough to make estimation potentially problematic (and it only shows up in `prep()`).
