### ISSUE TITLE
Re-licensing embed ✍️

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/embed#78]
We are systematically re-licensing tidymodels packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all non-RStudio [contributors](https://github.com/tidymodels/embed/graphs/contributors). 

@Athospd, @klahrich, @konradsemsch, would you permit us to re-license embed with the MIT license? If so, please comment "I agree" below.

* [x] [@Athospd](https://github.com/tidymodels/embed/commits?author=Athospd)  
* [x] [@klahrich](https://github.com/tidymodels/embed/commits?author=klahrich)  
* [x] [@konradsemsch](https://github.com/tidymodels/embed/commits?author=konradsemsch)

**Comment by konradsemsch** [comment]
hi @juliasilge ! Yes, I agree 😉

**Comment by klahrich** [comment]
Hi! Yes, I agree

**Comment by Athospd** [comment]
I agree!

**Comment by juliasilge** [comment]
Thank you, all! 🙏
